### ISSUE TITLE
Feature request: is it possible to save the Thumbnail preview Image from the push notifications? 

### ISSUE THREAD

**Issue by shifoc** [FunkyMuse/Vigilante#168]

**Comment by FunkyMuse** [comment]
I'm not sure why you closed and reopened this, also I'm not sure why you're wanting this as an option inside this app, the app doesn't focus on that, also what does push notifications have to do with any of this?

Sorry I'm confused about your request, can you try to explain a little bit more?

**Comment by shifoc** [comment]
Hi, sorry I closed it by mistake. Since your app already logs notifications I was also wondering if they can log the preview thumbnail example :
![Screenshot_20210409_025713.jpg](https://user-images.githubusercontent.com/32818143/114110074-54a28c80-98df-11eb-949d-24deb2d01726.jpg)

**Comment by FunkyMuse** [comment]
I don't really see how this fits as a feature in this app, I have to obtain the image, save it to the app's storage then provide the user with an option to view them since new Android changes won't let you save the file wherever you want, then he may want to export/transfer or use something X on the image, this app wasn't built with that in mind, probably the thumbnail you're receiving in the notification you'll receive it as a full image inside an app where you can download it as well, it doesn't make sense to support this.
