### ISSUE TITLE
Application Keeps Crashing

### ISSUE THREAD

**Issue by IamDeepx** [FunkyMuse/Vigilante#220]
Issue:

When trying to customize dot indicator for camera, microphone and location the application crashes. Also crashes when trying to view apps that requested a permission.

**Comment by FunkyMuse** [comment]
Go into crashes and copy paste the crash report, otherwise I can't help you

**Comment by FunkyMuse** [comment]
`` Stacktrace ``

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	... 1 more
Caused by: java.lang.NoSuchMethodException: c.a.i.k.b.fromBundle [class android.os.Bundle]
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getMethod(Class.java:1693)
	at j.r.f.getValue(:3)
	at com.crazylegend.vigilante.customization.CustomizationFragment.y0(:1)
	at com.crazylegend.vigilante.customization.CustomizationFragment.f0(Unknown Source:5)
	at j.m.b.h0.f(:11)
	at j.m.b.h0.k(:8)
	at j.m.b.a0.B(:19)
	at j.m.b.a0.W(Unknown Source:91)
	at j.m.b.a0.z(:4)
	at j.m.b.a0$d.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	... 3 more


`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 9
Thread time: 0 hr 0 min, 1 sec

`` END of thread info ``

`` Device info ``

Report ID: 87c955e8-77c3-41ce-b3f0-52c1acb4ede9
Device ID: e96a6a87f33435c3
Application version: 13
Default launcher: com.google.android.apps.nexuslauncher
Timezone name: Central European Standard Time
Timezone ID: Europe/Skopje
Version release: 11
Version incremental : 6934943
Version SDK: 30
Board: taimen
Bootloader: TMZ30m
Brand: google
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: taimen
Display: RP1A.201005.004.A1
Fingerprint: google/taimen/taimen:11/RP1A.201005.004.A1/6934943:user/release-keys
Hardware: taimen
Host: abfarm-01392
ID: RP1A.201005.004.A1
Manufacturer: Google
Product: taimen
Build time: 1603836852000
Build time formatted: 27-10-2020 23:14:12
Type: user
Radio: g8998-00034-2006052136
Tags: release-keys
User: android-build
User IDs: N/A
Is sustained performance mode supported: Yes
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 54
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc MSM8998
Number of CPU cores: 8
Up time with sleep: 7 hr 37 min, 7 sec
Up time without sleep: 2 hr 49 min, 54 sec

`` END of Device info ``

`` Exit reasons ``

N/A

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 13
Version name: 1.2.0
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: 80TIH8ebytS8JEoC2hG/5fpUBHo=
Is debuggable: No
First installed: 15-06-2021 20:26:02
Last updated: 15-06-2021 20:26:02
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: camera_pref_notifications = true, camera_pref_bypass_dnd = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false
Default prefs: camera_pref_notifications = true, camera_pref_bypass_dnd = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false

`` END of Application info ``


`` Currently running foreground/background processes ``

N/A

`` END of running foreground/background processes info ``

Is this the crash?

**Comment by FunkyMuse** [comment]
Will fix it in the upcoming release
