### ISSUE TITLE
Option to adjust indicator position based on x or y coordinate

### ISSUE THREAD

**Issue by Hx2-code** [FunkyMuse/Vigilante#57]
A feature like that will give more customization to the indicator icon

**Comment by FunkyMuse** [comment]
This ain't possible due to limitation by Android's view system always asking about a damn gravity in the window manager, I tried an implementation based on X and Y but it wouldn't draw them since it requires Gravity, then I calculated the gravity based on the X and Y and it didn't draw the dot at the X and Y respectively.
Eh well, worth a shot.

**Comment by Hx2-code** [comment]
Can you send me the code you modified? I think I have a way to make it possible.

**Comment by FunkyMuse** [comment]
> Can you send me the code you modified? I think I have a way to make it possible.
> […](#)
> On Jan 6, 2021, 9:02 PM, at 9:02 PM, FunkyMuse ***@***.***> wrote: This ain't possible due to limitation by Android's view system always asking about a damn gravity in the window manager, I tried an implementation based on X and Y but it wouldn't draw them since it requires Gravity, then I calculated the gravity based on the X and Y and it didn't draw the dot at the X and Y respectively. Eh well, worth a shot. -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#57 (comment)](https://github.com/FunkyMuse/Vigilante/issues/57#issuecomment-755368842)

I deleted the branch.

You can go ahead fork it and try to implement it on a separate branch
